Repository AY2425S1-CS2103T-W08-4/tp, pull requests merged in 2024-11, with the labels that each got.

#141 Group storage
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
Labels: priority.High, severity.High

#152 Write tests for jsonadaptedgroup
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
Labels: priority.Low

#153 Fix group command grammar
  src/main/java/seedu/address/logic/commands/GroupCommand.java
Labels: severity.VeryLow

#158 Fix bugs
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/GroupsWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/gb.png
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/GroupWindow.css
  src/main/resources/view/GroupWindow.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#162 Fix bug in AddressBookParser
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, alpha-bug

#163 Fix ug redo UI
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupsCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/GroupsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/images/gb.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/GroupWindow.css
  src/main/resources/view/GroupWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupsCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Enhancement, priority.High, severity.High

#170 Link delete and group functionality
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupList.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
Labels: priority.High

#174 Fix table formatting in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High, alpha-bug

#240 Branch refactor groups
  docs/UserGuide.md
  docs/images/ListGroup.png
  src/main/java/seedu/address/logic/commands/ListGroupsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ListGroupsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/GroupsUtil.java
Labels: priority.High, severity.High, alpha-bug

#258 Fix user guide issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Help.png
  docs/images/ListGroup.png
  docs/images/ListGroups.png
  docs/images/Untag.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#260 Fix tag and untag case sensitivity issue
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#276 Fix dg
  docs/DeveloperGuide.md
  docs/diagrams/DeleteGroupSequenceDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/GroupSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TagSequenceDiagram.puml
  docs/images/DeleteGroupSequenceDiagram.png
  docs/images/ExportSequenceDiagram.png
  docs/images/GroupSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TagSequenceDiagram.png
Labels: type.Bug

#277 Update TOC
  docs/DeveloperGuide.md
Labels: priority.Low
