Repository AY2425S1-CS2103T-W08-4/tp, pull requests merged in 2024-10, with the labels that each got.

#26 Add my details to AboutUs page
  docs/AboutUs.md
Labels: priority.High, severity.Low

#24 Update aboutUs to contain Wen Jie
  docs/AboutUs.md
Labels: priority.High, severity.VeryLow

#36 Update project website title
  docs/_config.yml
Labels: priority.High

#35 Update GitHub actions badge
  README.md
Labels: priority.High

#38 Add Ui.png mockup
  docs/images/Ui.png
Labels: priority.High, severity.Medium

#45 Update readme and dg
  README.md
  docs/DeveloperGuide.md
Labels: priority.High, severity.VeryLow

#52 Reformat add command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentClass.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High, severity.High

#49 Group feature for milestone 1.2
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/GroupUtil.java
Labels: type.Story, priority.High

#60 Add Export command and Export Command test
  build.gradle
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/data/JsonExportTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.High, severity.High

#64 Group testing
  .gitignore
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/GroupCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/testutil/GroupsUtil.java
Labels: type.Enhancement, priority.High

#77 Add Icon
  src/main/resources/images/address_book_32.png
  src/main/resources/images/address_book_33.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, severity.Low

#80 Fix bugs in export command and add more tests
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/data/JsonExportTest/accessDenied.json
  src/test/data/addressbook.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.High

#95 Update colors
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Low

#96 Add Group to puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.Low

#94 Refactor UI
  .gitignore
  build.gradle
  exported_data.csv
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupsCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindGroupCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/group/GroupList.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/GroupsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/GroupWindow.css
  src/main/resources/view/GroupWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/GroupsCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/group/GroupContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/group/GroupListTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalPaths.java
Labels: priority.Medium, severity.Medium

#107 Add the new activity diagram for FindGroupCommand and update FindCommand
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/FindGroupCommandActivityDiagram.puml
Labels: priority.Medium, severity.VeryLow

#105 Update user guide with new information
  docs/UserGuide.md
Labels: priority.Medium, severity.VeryLow

#118 Add section for findGroup Command in UG
  docs/UserGuide.md
Labels: priority.Low, severity.Low

#138 Add group command to user guide
  docs/UserGuide.md
Labels: priority.High

#140 Update images and DG
  docs/DeveloperGuide.md
  docs/images/BetterModelClassDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.Medium, severity.Low

#145 Fix bug where export command exports wrong place
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: priority.High, severity.High
